### ISSUE TITLE
Unable to install with Python3

### ISSUE THREAD

**Issue by Jamievs1** [konstantint/PassportEye#1]
I am unable to install this with python3, even after using 2to3.py. Any chance there is / will be python3 support?

**Comment by konstantint** [comment]
So far I did not find time for that. Not sure I'll have this time in the next month or two, but I'll certainly keep in mind there's at least one person interested in that feature :)

**Comment by better365** [comment]
I am also interested in Python 3.6. Thanks!

**Comment by katossi** [comment]
I´m interested as well

**Comment by ionspicica** [comment]
Is compatible with python 3?

**Comment by konstantint** [comment]
As of version 1.1.0 it is.
