### ISSUE TITLE
Recognize MRZ from pictures

### ISSUE THREAD

**Issue by alexandrubujor** [konstantint/PassportEye#14]
Hi,

I am trying to recognize MRZ from pictures taken of some of the identity documents. So far things are failing completely and I am trying to understand why. Is there any pre-processing that I could do on a picture taken with a phone, for example, to enhance the chance of recognising the MRZ?

Thanks,
Alex

**Comment by konstantint** [comment]
The proper way for debugging the situation would be to do:
```
from passporteye.mrz.image import MRZPipeline
p = MRZPipeline(filename)
mrz = p.result
```
and then study the various components of the `p` object: `p["img_small"]`, `p["img_binary"]` and `p["boxes"]`. These are created by the various steps of the pipeline and might help indicate what seems wrong with the image.

The `img_small` and `img_binary` are arrays which you can display via matplotlitb's `imshow` when working with a Jupyter notebook.

**Comment by alexandrubujor** [comment]
Hi @konstantint ,

Thanks a lot for your answer! I tried the commands, but the p["boxes"] is empty.

```
>>> p["img_small"]
array([[0.93879866, 0.90578094, 0.76636904, ..., 0.34936272, 0.36049689,
        0.3602394 ],
       [0.92792023, 0.85410285, 0.79856261, ..., 0.35947953, 0.36080753,
        0.35985742],
       [0.93051895, 0.88866086, 0.77952351, ..., 0.35621378, 0.31954328,
        0.35564315],
       ...,
       [0.36136673, 0.41491568, 0.44051584, ..., 0.54580722, 0.5559503 ,
        0.55070275],
       [0.35477256, 0.4255493 , 0.4245245 , ..., 0.5500617 , 0.56387781,
        0.56887372],
       [0.39892818, 0.39206542, 0.41955632, ..., 0.53693529, 0.56063509,
        0.53998494]])
>>> p["boxes"]
[]
>>> p["img_binary"]
array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])
>>> ^D
```

Could that mean something specific?

Thanks,
Alex

**Comment by alexandrubujor** [comment]
Binary Image looks like this:
<img width="583" alt="screen shot 2018-04-28 at 15 34 22" src="https://user-images.githubusercontent.com/34791321/39396602-ba8fdeee-4af9-11e8-8c8e-a12913b242b7.png">

**Comment by alexandrubujor** [comment]
And small image:

<img width="580" alt="screen shot 2018-04-28 at 15 36 10" src="https://user-images.githubusercontent.com/34791321/39396618-ea499c2e-4af9-11e8-976b-f2a96a9e2d49.png">

**Comment by konstantint** [comment]
What you see on the binary mask is the region with high variability on a picture - it would typically correspond to the MRZ and is extracted via the method documented [here](https://www.pyimagesearch.com/2015/11/30/detecting-machine-readable-zones-in-passport-images/).

In your case there seems to be too much variability outside the MRZ (both the background as well as within the document itself), hence the used approach simply does not work just as well.

It is somewhat up to you to figure out a way to filter out the various noises in the image and leave just the MRZ. I'd guess a neural network based detector would be a decent and robust solution but so far never found the time to train one myself.

**Comment by alexandrubujor** [comment]
Thanks you very much, @konstantint . Appreciate your answer.
