### ISSUE TITLE
Improving the quality of the result

### ISSUE THREAD

**Issue by KayHS** [konstantint/PassportEye#20]
I am trying to read the data from a passport.
```
        filename = "passport_example_post.png"
        mrz = read_mrz(filename, save_roi=True)
        pprint(mrz.to_dict())
```
**result**
```
{
    "Images": {
        "mrz_type": "TD2",
        "valid_score": 2,
        "type": "SA",
        "country": "NEA",
        "number": "6£SS06601",
        "date_of_birth": "Y0L¥00",
        "expiration_date": "5Y60Y<",
        "nationality": "—AA",
        "sex": "S",
        "names": "",
        "surname": "ILGIUTASSSOU—_—",
        "optional1": "<<<<<<<",
        "check_number": "L",
        "check_date_of_birth": "3",
        "check_expiration_date": "<",
        "check_composite": "<",
        "valid_number": false,
        "valid_date_of_birth": false,
        "valid_expiration_date": false,
        "valid_composite": false
    }
}
```

however it looks like its having a hard time reading the mrz from the passport image. 

The above result is after converting the image to grayscale, increasing both the brightness and contrast of the image by 100%. After this all the characters of the mrz in the image are clearly visible.

**Comment by konstantint** [comment]
Try running the command-line `mrz` tool with the `--save-roi` option, i.e.:
```
mrz <image.jpg> --save-roi <roi.png>
```
Then check out the `roi.png` to see the exact part used in the OCR process (it is fed directly into Tesseract without any more serious processing). Most probably it will be either too small or too large or rotated or smth like that, but perhaps it will give you a hint as what is the problem with the original image.

**Comment by KKHAN1991** [comment]
Yep, its upside down and does not contain the MRZ code found at the bottom of the passport...

**Comment by konstantint** [comment]
Are you sure the original image oriented correctly? Note that JPG photos where the correct orientation is stored in the EXIF header are not automatically rotated to that orientation, i.e. you'd need to actually rotate and save the image so that its upper left corner would be in the upper left of its bitmap as stored.
