### ISSUE TITLE
Return raw MRZ along with parsed data

### ISSUE THREAD

**Issue by peterhorsley** [konstantint/PassportEye#26]
It would be useful in some cases for a consumer to be able to receive the raw MRZ text, for example, to be used as an identifier, but currently, only the parsed fields along with some metadata are provided.  There is a flag that allows the caller to access the region-of-interest image, which is handled like this:

   if save_roi: mrz.aux['roi'] = p['roi']

So it looks pretty straightforward to add another flag like save_raw_mrz or similar to include this data, or it could be added by just be default with no flags.  This is kind of similar to #5, but I think a little different.

Happy to create a PR for this enhancement if you see this as useful!  Thanks!

**Comment by konstantint** [comment]
OK. Added `mrz.aux['text'] = p['text']` there, perhaps it might be useful sometimes.

**Comment by konstantint** [comment]
Also in 1.3.0 now.

**Comment by peterhorsley** [comment]
Fantastic, thanks!
