### ISSUE TITLE
Add auto-rotate (understanding how to add a component to the pipeline)

### ISSUE THREAD

**Issue by chrisvwn** [konstantint/PassportEye#28]
Admittedly, I am new to python and passporteye so this may be a newbie issue.

Despite the time it will take to return a result, I am experimenting with adding a component to rotate the image 90 degrees if no mrz is found and to rerun the pipeline. In my understanding, if the image is rotated on its side this will either right-side it or turn it upside down and in either case the pipeline should be able to handle locating and extracting the mrz.

Looking at the try_other_width component, I have tried to add a new component that calls a modified loader with a rotate_img parameter.

The new loader code:
```
class Loader(object):
    """Loads `file` to `img`."""

    __depends__ = []
    __provides__ = ['img']

    def __init__(self, file, as_gray=True, pdf_aware=True, rotate_img=False):
        self.file = file
        self.as_gray = as_gray
        self.pdf_aware = pdf_aware
        self.rotate_img = rotate_img

    def _imread(self, file):
        """Proxy to skimage.io.imread with some fixes."""
        # For now, we have to select the imageio plugin to read image from byte stream
        # When ski-image v0.15 is released, imageio will be the default plugin, so this
        # code can be simplified at that time.  See issue report and pull request:
        # https://github.com/scikit-image/scikit-image/issues/2889
        # https://github.com/scikit-image/scikit-image/pull/3126
        img = skimage_io.imread(file, as_gray=self.as_gray, plugin='imageio')
        if img is not None and len(img.shape) != 2:
            # The PIL plugin somewhy fails to load some images
            img = skimage_io.imread(file, as_gray=self.as_gray, plugin='matplotlib')
            if rotate_img:
                img = np.rot90(img)

        return img

    def __call__(self):
        if isinstance(self.file, str):
            if self.pdf_aware and self.file.lower().endswith('.pdf'):
                with open(self.file, 'rb') as f:
                    img_data = extract_first_jpeg_in_pdf(f)
                if img_data is None:
                    return None
                return self._imread(img_data)
            else:
                return self._imread(self.file)
        elif isinstance(self.file, (bytes, io.IOBase)):
            return self._imread(self.file)
        return None
```

the new class to replace the loader with the rotate_img parameter:
```
class TryRotatedImage(object):
    """
    If mrz was not found so far in the current pipeline,
    changes the loader to rotate the image 90 degrees. If image on the side it should right side it or upside down it both of which should
    be detected by the workflow.
    """

    __provides__ = ['mrz_final1']
    __depends__ = ['mrz', '__pipeline__']

    def __init__(self, rotate_img=True):
        self.rotate_img = rotate_img

    def __call__(self, mrz, __pipeline__):
        if mrz is None:
            import pdb; pdb.set_trace()
            __pipeline__.replace_component('loader', Loader(file, rotate_img=self.rotate_img))
            new_mrz = __pipeline__['mrz']
            if new_mrz is not None:
                new_mrz.aux['method'] = new_mrz.aux['method'] + '|rotated img'
            mrz = new_mrz
        return mrz
```
and the modified pipeline:
```
class MRZPipeline(Pipeline):
    """This is the "currently best-performing" pipeline for parsing MRZ from a given image file."""

    def __init__(self, file, extra_cmdline_params=''):
        super(MRZPipeline, self).__init__()
        self.version = '1.0'  # In principle we might have different pipelines in use, so possible backward compatibility is an issue
        self.file = file
        self.add_component('loader', Loader(file))
        self.add_component('scaler', Scaler())
        self.add_component('boone', BooneTransform())
        self.add_component('box_locator', MRZBoxLocator())
        self.add_component('mrz', FindFirstValidMRZ(extra_cmdline_params=extra_cmdline_params))
        self.add_component('other_max_width', TryOtherMaxWidth())
        self.add_component('rotated_image', TryRotatedImage(file))

    @property
    def result(self):
        return self['mrz_final']
```
Is this going in the right direction? A couple of issues I do not understand:
1) What key should class `TryRotatedImage` have in `__provides__`? Trying to  put in `mrz_final` which seems like the right thing since the pipeline returns `self['mrz_final']` gives an error that the key is already provided by another component.
2) If I try to pass the `rotate_img` argument in the line `self.add_component('rotated_image', TryRotatedImage(file, rotate_img=True))` gives me the error `TypeError: __init__() got multiple values for keyword argument 'rotate_img'`

Any help would be appreciated.

**Comment by konstantint** [comment]
I must admit that whole "TryOther..." business is a very hackish solution. It was made on a whim, and I don't really like it, but don't have the time now to rethink it into something more reasonable.

Here's how things work: the Pipeline class basically stores a computation graph of the form 

    (image) -> (loaded image) -> (transformed image) -> ... -> (mrz)

At some point I discovered that if mrz is not found it may make sense to try repeating the whole pipeline with a different width. Now, this kind of computation does not fit the "stateless" logic of the pipeline anymore and to implement it I should have probably changed the logic to a kind of a "smarter" pipeline, which can clone its branches somehow. But there was no time, so instead a hack was implemented. Namely, I appended an extra step to the pipeline:

(mrz) -> (mrz_final).

This step, when invoked, checks whether mrz is None and if so (+one extra condition), replaces the "Scaler" component of the pipeline, invalidating everything which was computed after it, and then re-runs the pipeline again. You may try to repeat this kind of hack and add a new TryRotation component to the end:
(mrz_final) -> (mrz_extra_final)
which may do something like "if mrz_final is none, then invalidate the part of the pipeline after the loaded image, rotate the image, and recompute the mrz_final value"
This might be simple, but super-hackish and not worth it, in my opinion.

A somewhat simpler solution would be to add rotation parameter to the pipeline as you did and then simply try running the pipeline with two different settings, e.g. something like
```
mrz = p.result
if not mrz:
    p.components['loader'].rotate_img = True
    p.invalidate('img')
    mrz = p.result

```
This assumes you have your own code and do not care for the built-in `mrz` script.

Finally, a proper solution would be to revise the whole Pipeline concept and add support for iteration there, but this would need some thinking through.

**Comment by chrisvwn** [comment]
Thank you for the response! This makes perfect sense. If my python were better I might have volunteered to assist with the Pipeline concept revision.

I think the second solution running the pipeline with two different settings is the better way to go. Although, I will probably try to run both just for the practice.
