### ISSUE TITLE
Nothing detected

### ISSUE THREAD

**Issue by zhouhao27** [konstantint/PassportEye#35]
I tried to detect the ID card like this:

![DogIC](https://user-images.githubusercontent.com/8099731/58679452-17414f80-8396-11e9-8d47-00502b81d199.jpg)

By:

> mrz --json DogIC.jpg

But it returns:

```
{
  "mrz_type": null,
  "valid": false,
  "valid_score": 0,
  "walltime": 0.5015320777893066,
  "filename": "DogIC.jpg"
}

```

Got the same result for other similar images. What could be the reason? Thanks.

**Comment by konstantint** [comment]
A MRZ (machine-readable zone) is this specific region with a bunch of ">>" characters on a document:
![image](https://user-images.githubusercontent.com/220083/58745397-bdea2680-8450-11e9-8687-e25372889909.png)

Your example does not have it. Oftentimes identity cards would have their MRZ on the back.
