### ISSUE TITLE
The < character is recognized as K

### ISSUE THREAD

**Issue by neumartin** [konstantint/PassportEye#36]
Several times the < character is recognized as K, how can I improve this?

**Comment by konstantint** [comment]
Try using the "legacy" Tesseract version, it seems to be somewhat better on average.
In theory, training a dedicated OCR model for the OCR-B font should help as well, however I haven't personally had any reliable results on this field yet and the legacy recognizer that comes out of the box is still pretty good.

Secondly, the better is the quality of your image, the better the recognition.

Finally, it might be possible to implement some postprocessing of the text (e.g. force-convert K-s to <'s in the regions of text where we expect to have <'s), however this is not on my agenda at the moment.

**Comment by SaddamBInSyed** [comment]
hi @konstantint 
thanks for your work.

"Try using the "legacy" Tesseract version,"

- How can I use the legacy version of the tesseract in the python app.

I am facing an accuracy issue. ( valid_score is 100 but the mrz value contains the inaccurate values)

please advise

**Comment by SaddamBInSyed** [comment]
I found.

just passing the extra_cmdline_params='--oem 0') will enable the legacy mode

Am i right?

Thanks
