### ISSUE TITLE
Not able to Scan mrz

### ISSUE THREAD

**Issue by satispande** [konstantint/PassportEye#40]
Hi,
![1](https://user-images.githubusercontent.com/36110282/65958662-8bd3ea00-e46d-11e9-9922-6b345d08fc05.jpg)

For the above attached sample the scan fails.
can you please let me know what can i do to get information if user upload's this kind of image or if the rotation is different.
Any hint would be appreciated.

**Comment by AnkBurov** [comment]
Well, you could modify the segmentation algorithm by adding Hough transformation to detect lines and also use a trained for MRZ Tesseract model. For example a recognition result of the photo above: 
```
check_composite = {str} '8'
check_date_of_birth = {str} '4'
check_expiration_date = {str} '1'
check_number = {str} '4'
check_personal_number = {NoneType} None
country = {str} 'IND'
date_of_birth = {str} '590923'
expiration_date = {str} '211010'
mrz_type = {str} 'TD3'
names = {str} 'SITA MAHA LAKSHMI'
nationality = {str} 'IND'
number = {str} 'J8369854'
personal_number = {NoneType} None
sex = {str} 'F'
surname = {str} 'RAMADUGULA'
type = {str} 'P'
valid = {bool} True
valid_check_digits = {list} <class 'list'>: [True, True, True, True, True]
valid_composite = {bool} True
valid_date_of_birth = {bool} True
valid_expiration_date = {bool} True
valid_line_lengths = {list} <class 'list'>: [True, True]
valid_misc = {list} <class 'list'>: [True]
valid_number = {bool} True
valid_personal_number = {bool} True
valid_score = {int} 100
```

**Comment by hunaidkhan2000** [comment]
@AnkBurov  how can i use pretrained MRZ data which i found on [(https://github.com/Shreeshrii/tessdata_ocrb)]. I need to compile it with tesseract or i can use it directly with passporteye?
