### ISSUE TITLE
"Failed loading language 'eng' Tesseract couldn't load any languages! Could not initialize tesseract."

### ISSUE THREAD

**Issue by Uysim** [konstantint/PassportEye#41]
```python
mrz = read_mrz("/content/demo.png", extra_cmdline_params='--oem 0', save_roi=True)
```
I got the error message 
```
Failed loading language 'eng' Tesseract couldn't load any languages! Could not initialize tesseract.
```
The problem is because `--oem 0`

**Comment by konstantint** [comment]
Yes, this stems from the fact that Tesseract often comes without legacy classifier data preinstalled, yet legacy classifiers tend to work better for MRZ recognition. Installing the appropriate data files or disabling the legacy mode (by specifying `--oem 3` in the `extra_cmdline_params`) would resolve the issue. I recommend the former. See [this comment](https://github.com/konstantint/PassportEye/issues/27#issuecomment-449713324) also.
