### ISSUE TITLE
how can i use passport eye for multiple images

### ISSUE THREAD

**Issue by hunaidkhan2000** [konstantint/PassportEye#45]
Hi,
first of all  thanks for creating such a useful package.
What i am trying is to import all the images from a particular folder with MRZ data. and run passport eye algorithm and finally all the saved result will be saved in a dataframe. so does this package support bulk upload of images?

**Comment by konstantint** [comment]
This is a python library, which provides a function that you can use to extract information from a given image. You are free to run this function in whatever way you find convenient, e.g. in a loop over a list of files from a folder. Note that each recognition is usually rather time-consuming, hence you might want to consider parallelizing such a workflow.

**Comment by hunaidkhan2000** [comment]
Thanks for the reply
