### ISSUE TITLE
choosing tessdata to get  more accuracy

### ISSUE THREAD

**Issue by SaddamBInSyed** [konstantint/PassportEye#46]
Hi @konstantint 

Thanks for your work.
I am using this lib to extract MRZ values from the National ID.
I am not satisfied with the current performance which I am getting from this MRZPipeline() class.
so I would like to ask

1.  How to improve my accuracy.
2.  How to use the tessdata_best trained files?

I have installed tesseract 4.0 (tesseract-ocr-setup-4.00.00dev.exe)  setup and I get the below  files in tessdata folder

![image](https://user-images.githubusercontent.com/10062672/77912448-a44d8180-72a3-11ea-91f9-da5db1b19a7b.png)

please advise

**Comment by konstantint** [comment]
Try specifying `extra_cmdline_params="-l osd"` (assuming `osd.traineddata` is the new model you created).
