### ISSUE TITLE
Differece of data when used by command line and with python code

### ISSUE THREAD

**Issue by MitaliGetafix** [konstantint/PassportEye#48]
Hi,
When I used the command :
mrz --json media/emiratesid_back.jpeg 
It return all the data extracted using MRZ code.
But when I use the same image in my code:
mrz = read_mrz("media/emiratesid_back.jpeg ")
it retunrs : MRZ(TD1[75], 190240230, AHMAD MOHAMAD, ABDULLAH, M, 680727)

Why is the difference ? I need all the data instead of only cardNo, firstname, lastname, gender and date of birth, apart from that expiryDate, IDNo are important data to scan from MRZ.

Can anyone please help?

**Comment by konstantint** [comment]
The `read_mrz` function returns an [`MRZ` object](https://github.com/konstantint/PassportEye/blob/4211f535e2ba1e450ba5c3f7adbc96ccb1929d88/passporteye/mrz/text.py#L12), which contains exactly the same information you see when you run the command line script. You can access the needed values via the corresponding fields of the object. You can also call `.to_dict()` to convert the MRZ object to a dictionary, if you feel more comfortable working with it.

The representation for the MRZ object that you obtain by calling the `__repr__` method (e.g. by just printing the object) is not displaying all the fields. This was a deliberate choice to favor more compact debug outputs.
