### ISSUE TITLE
Evaluation and Benchmarking

### ISSUE THREAD

**Issue by abhianand7** [konstantint/PassportEye#51]
Version: PassportEye==1.4.1

I am trying to Benchmark the results of PassportEye for mrz data extraction from passports.

Currently, when I use evaluate_mrz, I get below output:

INFO:evaluate_mrz:Preparing computation for 6 files from examples/
INFO:evaluate_mrz:Running 8 workers
INFO:evaluate_mrz:Processed passport1.jpg in 0.65s (score 0) [?]
INFO:evaluate_mrz:Processed my_passport.jpg in 1.18s (score 100) [?]
INFO:evaluate_mrz:Processed passport3.jpg in 1.97s (score 44) [?]
INFO:evaluate_mrz:Processed passport.jpeg in 2.21s (score 40) [?]
INFO:evaluate_mrz:Processed passport4.jpg in 2.22s (score 100) [?]
INFO:evaluate_mrz:Processed passport2.png in 2.29s (score 61) [?]
INFO:evaluate_mrz:Completed
Walltime:          2.32s
Compute walltime:  10.52s
Processed files:   6
Perfect parses:    2
Invalid parses:    1
Improved parses:   0
Worsened parses:   0
Total score:       345
Mean score:        57.50
Mean compute time: 1.75s
Methods used:
  direct: 4
  rescaled(3): 1
(venv) zero@TimeMachine2:~/PycharmProjects/MrzOcr$ evaluate_mrz -j 8 -dd examples/
INFO:evaluate_mrz:Preparing computation for 10 files from examples/
INFO:evaluate_mrz:Running 8 workers
INFO:evaluate_mrz:Processed passport1.jpg in 1.35s (score 0) [?]
INFO:evaluate_mrz:Processed passport-td2.png in 3.51s (score 100) [?]
INFO:evaluate_mrz:Processed my_passport.jpg in 7.93s (score 100) [?]
INFO:evaluate_mrz:Processed passport-td2.jpg in 9.59s (score 97) [?]
INFO:evaluate_mrz:Processed passport-td3.png in 11.95s (score 98) [?]
INFO:evaluate_mrz:Processed passport3.jpg in 10.72s (score 44) [?]
INFO:evaluate_mrz:Processed passport.jpeg in 12.19s (score 40) [?]
INFO:evaluate_mrz:Processed passport2.png in 12.24s (score 61) [?]
INFO:evaluate_mrz:Processed passport4.jpg in 8.83s (score 100) [?]
INFO:evaluate_mrz:Processed passport-td3.jpg in 12.65s (score 98) [?]
INFO:evaluate_mrz:Completed
Walltime:          12.69s
Compute walltime:  90.97s
Processed files:   10
Perfect parses:    3
Invalid parses:    1
Improved parses:   0
Worsened parses:   0
Total score:       738
Mean score:        73.80
Mean compute time: 9.10s
Methods used:
  direct: 8
  rescaled(3): 1

How to interpret this info exactly?
And is the score mentioned above the confidence at which data was extracted?

Any help would be really great. Thank you

**Comment by konstantint** [comment]
PassportEye has a notion of a `score`, assigned to the recognized image. It is an ad-hoc measure, indicating the quality of the result, computed as a weighted sum of various checksum digits. The score of 100 denotes a most probably perfect recognition. A score of 0 usually means nothing was found. Scores inbetween show that some of the values might have been recognized correctly, but not all of them. The output you see reports a score value near each image. At the very end you can also see the total and mean score - those help understand whether changes you made to the algorithm improved it on your dataset.

Similarly, walltime and compute walltime indicate the time it took to run the computation and are useful to see whether a newly developed feature made the algorithm much slower.

Perfect parses indicates the number of 100-scored files. Invalid parses indicates the number of 0-scored files. The "Improved" and "worsened" parses compare the scores you got in this run with "previously known" scores. A "previously known" score, if you want to make use of it, has to be encoded in the image name in the form `<previous score>_whatever.jpg`. Take a look at `passporteye/mrz/testdata` for an illustration.

The "Methods used" section lists the various hacks that the algorithm tried in the process of detection. In your case it means that 8 images were processed as-is, and 3 had to go through an attempted rescaling.

Hope this helps.
