### ISSUE TITLE
Installation with 'pip' won´t work

### ISSUE THREAD

**Issue by katossi** [konstantint/PassportEye#6]
Hi,

I´m trying to install PassportEye in a Windows and a linux (Ubuntu 16.04) machines but it fails in both. Before I provide more information I´d like to know if the project is still alive and the installer should be working.

Guille

**Comment by konstantint** [comment]
As you must have seen in a neighboring issue, the package is not adapted for Python 3 at the moment. It should be installable under Python 2.

**Comment by katossi** [comment]
I though that could be the issue and retried with python 2.7. Still experiencing issues in ubuntu. Many python modules won´t install with pip and I ended up mixing 'apt-get' for some and 'pip' for others. After all that it seemed to work, but not the server.

**Comment by konstantint** [comment]
The most common reason for such problems is mixing `sudo` and non-`sudo` commands (e.g. many people would automatically write `sudo apt install` but `pip install`).

In general, I personally prefer to first set up a local `virtualenv`, and then install everything into this virtualenv using a non-sudo `pip`, this is usually the most reliable approach.

Mixing `apt`, `pip` and `conda` packages is a sure recipe for confusion.

**Comment by katossi** [comment]
Thanks a lot for the tip! Actually most of my problems came from 'MemoryError' problems with some packages like Scipy. Adding the '--no-cache-dir' option as mentioned below seems to do the trick.

https://stackoverflow.com/questions/29466663/memory-error-while-using-pip-install-matplotlib

**Comment by konstantint** [comment]
I think that one of the best Python installations for practical purposes nowadays is Anaconda Python. You unpack it into the user's directory (hence no worries with `sudo`-ing) and it has all the data-wrangling batteries (such as numpy and scipy) included already.

**Comment by sri12ram** [comment]
Facing issues in installing this on Anaconda python (even a 2.7 version).  How do I install on Anaconda?

**Comment by katossi** [comment]
First install the dependencies that PassportEye required and in the end install it with pip. It worked perfect for me both in Linux and Windows!

**Comment by sri12ram** [comment]
Thanks!  I had problems on Mac.  Now, it's working.
