### ISSUE TITLE
Document recognition does not work.

### ISSUE THREAD

**Issue by AraKchrUser** [konstantint/PassportEye#61]
Thank you very much for your work! I am writing a thesis where I want to apply your development. I've experimented with library versions, including sk image, but nothing helps.

mrz_type        None
valid   False
valid_score     0
walltime        0.36080217361450195
filename        1.JPG

**Comment by konstantint** [comment]
The most common reasons for the library to fail to recognize are:
 - Anything on the image besides the document (e.g. if you simply photo your document lying on a table next to other things, the recognition may fail to find the correct location).
 - Unfortunate rotation (for best results, have the document horizontal or vertical on the page).
 - Bad resolution (the current algorithm supports a limited range of "sane" resolutions).
 - Blurry image
 - Very non-standard document.

In general, it is hard to pinpoint the actual reason without looking at the document, but I hope you should be able to understand the reasons if you compare your image to the photos in the https://github.com/konstantint/PassportEye/tree/master/passporteye/mrz/testdata directory - those with a prefix of 100 in the filename are known to be recognizeable.

**Comment by AraKchrUser** [comment]
Thanks a lot for the answer, I figured it out. You were right, it was necessary to select the image well.

**Comment by AraKchrUser** [comment]
Thanks a lot for the answer, I figured it out. You were right, it was
necessary to select the image well.

пн, 17 янв. 2022 г. в 20:17, Konstantin Tretyakov ***@***.***
