### ISSUE TITLE
Where is photomanipulation detection performed?

### ISSUE THREAD

**Issue by buabaj** [konstantint/PassportEye#68]
From the [documentation](https://passporteye.readthedocs.io/en/latest/image_manipulation.html), it says passporteye performs error level analysis for possible manipulation detection. I'd like to know where this is explicitly performed please.

**Comment by konstantint** [comment]
The documentation you point to is apparently for [this fork](https://github.com/CRImier/PassportEye/tree/server) of this project. Unfortunately, I am not aware about the details of that codebase and could not comment on what is happening there.
