### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'aux'

### ISSUE THREAD

**Issue by ionspicica** [konstantint/PassportEye#8]
![fd0](https://user-images.githubusercontent.com/13585500/34215530-3f9a103e-e5ae-11e7-9702-5e13ddd1cf51.png)
When the image is large

image.py", line 297, in __call__
    new_mrz.aux['method'] = new_mrz.aux['method'] + '|max_width(%d)' % self.other_max_width
AttributeError: 'NoneType' object has no attribute 'aux'

**Comment by konstantint** [comment]
I can't reproduce this with the attached image. At least `mrz test.png` works fine.

**Comment by ionspicica** [comment]
With command line work without problems. Please try from the code using the read_mrz method

**Comment by konstantint** [comment]
I see. The None result was not passed through. Fixed.
