### ISSUE TITLE
 module 'pytesseract.pytesseract' has no attribute 'tempnam'

### ISSUE THREAD

**Issue by idobrodushniy** [konstantint/PassportEye#9]
Have got this issue, when tried to run mrz_read. The tesseract is accessible via console..
Exception Value: module 'pytesseract.pytesseract' has no attribute 'tempnam'

**Comment by idobrodushniy** [comment]
Issue solved by downloading the https://github.com/madmaze/pytesseract/releases/tag/v0.1.7 release of pytesseract. @konstantint , please, can you put into requirements of passporteye the pytesseract==0.1.7 or update the code of pytesseract.

**Comment by mwh1te** [comment]
Thanks for figuring this out. pytesseract 0.1.7 works for me as well.

**Comment by hokmund** [comment]
Added a hotfix in the pull request #10
